import test from 'node:test';
import assert from 'node:assert/strict';
import {AudioBank} from '../studio/audio.js';
const object={id:'object-1',interaction:{soundId:'sound-1',volume:.4}},sounds=[{id:'sound-1',src:'sound.wav',name:'Sound'}];
const fetcher=async()=>new Response(new Uint8Array([1,2,3]));
function context(){let finish;const c={state:'suspended',started:0,stopped:0,decodeAudioData:async b=>b,resume(){return new Promise(r=>finish=()=>{c.state='running';r();});},release(){finish();},createGain(){return{gain:{value:0},connect(){return this;}};},createBufferSource(){return{connect(){return this;},start(){c.started++;},stop(){c.stopped++;}};},destination:{}};return c;}
test('Web Audio waits for resume before starting and applies configured gain',async()=>{const c=context(),bank=new AudioBank(x=>x,{createContext:()=>c,fetcher});await bank.load(sounds);const p=bank.play(object);assert.equal(c.started,0);c.release();assert.equal(await p,true);assert.equal(c.started,1);bank.stopAll();assert.equal(c.stopped,1);});
test('scene stop cancels pending audio resume so old scene never emits delayed sound',async()=>{const c=context(),bank=new AudioBank(x=>x,{createContext:()=>c,fetcher});await bank.load(sounds);const p=bank.play(object);bank.stopAll();c.release();assert.equal(await p,false);assert.equal(c.started,0);});
function native(){return{readyState:1,src:'',volume:1,muted:true,paused:true,plays:0,pauses:0,currentTime:0,setAttribute(){},removeAttribute(){},load(){},play(){this.plays++;this.paused=false;return Promise.resolve();},pause(){this.pauses++;this.paused=true;}};}
test('AR media play is called inside gesture synchronously, before Promise continuation; stop and mute release it',async()=>{const players=[],bank=new AudioBank(x=>x,{mode:'media',createMedia:()=>{const a=native();players.push(a);return a;},fetcher});await bank.load(sounds);bank.prepare([object]);assert.equal(players.length,1);const p=bank.play(object);assert.equal(players[0].plays,1);assert.equal(players[0].muted,false);assert.equal(players[0].volume,.4);assert.equal(await p,true);bank.stopAll();assert.equal(players[0].paused,true);bank.enabled=false;assert.equal(await bank.play(object),false);assert.equal(players[0].plays,1);});
test('objects sharing one sound use separate media players and repeat tap stops previous instance',async()=>{const players=[],bank=new AudioBank(x=>x,{mode:'media',createMedia:()=>{const a=native();players.push(a);return a;},fetcher});await bank.load(sounds);const other={...object,id:'object-2'};bank.prepare([object,other]);await bank.play(object);await bank.play(other);assert.equal(players.length,2);assert.ok(players.every(p=>!p.paused));await bank.play(object);assert.equal(players[0].plays,2);assert.equal(players[0].pauses,1);bank.stop(object.id);assert.equal(players[0].paused,true);assert.equal(players[1].paused,false);});
test('rejected native playback reports failure and cannot pretend success; ended sound releases source',async()=>{const a=native();a.play=()=>Promise.reject(new Error('NotAllowedError'));const bank=new AudioBank(x=>x,{mode:'media',createMedia:()=>a,fetcher});await bank.load(sounds);await assert.rejects(bank.play(object),/音声を開始できません/);assert.equal(bank.sources.size,0);a.play=()=>Promise.resolve();await bank.play(object);a.onended();assert.equal(bank.sources.size,0);});
test('default fetch uses the global receiver required by Safari rather than AudioBank',async()=>{const original=globalThis.fetch;let calls=0;try{globalThis.fetch=function(url){assert.equal(this,globalThis);assert.equal(url,'sound.wav');calls++;return Promise.resolve(new Response(new Uint8Array([1,2,3])));};const bank=new AudioBank(x=>x,{mode:'media',createMedia:native});await bank.load(sounds);assert.equal(calls,1);assert.equal(bank.buffers.get('sound-1'),'sound.wav');}finally{globalThis.fetch=original;}});
