import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';import {STEPS,WORKSPACES,reactionText} from '../studio/workflow.js';
// DOM contract test: real setupGuide source runs against a minimal DOM, not a rendering/browser test.
class Node {
 constructor(tag='#text',text=''){this.tagName=tag.toUpperCase();this.nodeType=tag==='#text'?3:1;this.childNodes=[];this.parentNode=null;this.attrs={};this._text=text;this.disabled=false;this.hidden=false;this.dataset={};this.classList={toggle:()=>{}};}
 setAttribute(k,v){this.attrs[k]=String(v);if(k==='id')this.id=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5)]=String(v);}
 get textContent(){return this._text+this.childNodes.map(n=>n.textContent).join('');}set textContent(v){this._text=String(v);this.childNodes=[];}
 detach(){if(this.parentNode)this.parentNode.childNodes=this.parentNode.childNodes.filter(n=>n!==this);}
 append(...nodes){for(let n of nodes){if(typeof n==='string')n=new Node('#text',n);n.detach();n.parentNode=this;this.childNodes.push(n);}}
 prepend(...nodes){for(const n of [...nodes].reverse()){n.detach();n.parentNode=this;this.childNodes.unshift(n);}}
 replaceChildren(...nodes){for(const n of this.childNodes)n.parentNode=null;this.childNodes=[];this.append(...nodes);}
 after(node){const p=this.parentNode;node.detach();node.parentNode=p;p.childNodes.splice(p.childNodes.indexOf(this)+1,0,node);}
 contains(node){return node===this||this.childNodes.some(n=>n.contains(node));}
 closest(tag){for(let n=this;n;n=n.parentNode)if(n.tagName===tag.toUpperCase())return n;return null;}
 querySelector(sel){return all(this).find(n=>match(n,sel))||null;}
 set innerHTML(html){this.replaceChildren(...parse(html).childNodes.slice());}get innerHTML(){return this.textContent;}
}
function all(n){return [n,...n.childNodes.flatMap(all)];}function match(n,s){if(s==='main>aside')return n.tagName==='ASIDE'&&n.parentNode?.tagName==='MAIN';if(s==='aside.right')return n.tagName==='ASIDE'&&n.attrs.class==='right';if(s.startsWith('[data-'))return s.slice(1,-1) in n.attrs;return n.tagName===s.toUpperCase();}
function parse(html){const root=new Node('root'),stack=[root];for(const token of html.match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){if(stack.length>1)stack.pop();}else if(token.startsWith('<!'))continue;else if(token.startsWith('<')){const m=/^<([\w-]+)/.exec(token);if(!m)continue;const n=new Node(m[1]);for(const a of token.matchAll(/([\w-]+)="([^"]*)"/g))n.setAttribute(a[1],a[2]);stack.at(-1).append(n);if(!['input','meta','link','br','img','hr'].includes(m[1])&&!token.endsWith('/>'))stack.push(n);}else stack.at(-1).append(new Node('#text',token));}return root;}
test('three integrated workspaces retain all existing form IDs; status stays visible; placement and reaction controls have separate parents',async()=>{const html=await readFile(new URL('../studio.html',import.meta.url),'utf8'),source=await readFile(new URL('../studio/editor.js',import.meta.url),'utf8');const root=parse(html);const document={createElement:tag=>new Node(tag),getElementById:id=>all(root).find(n=>n.id===id)||null,querySelector:s=>root.querySelector(s),querySelectorAll:s=>all(root).filter(n=>match(n,s))};const before=all(root).filter(n=>n.id).map(n=>n.id);const p={title:'test',sounds:[],scenes:[]};const context=vm.createContext({document,STEPS,WORKSPACES,reactionText,project:p,scene:{name:'シーン1',objects:[]},selected:null,session:null,publishedURL:'',publishedFingerprint:'',activeStep:0,marker:()=>null,$:id=>document.getElementById(id)});vm.runInContext(source.slice(source.indexOf('function element('))+'\nsetupGuide();',context);for(const id of before)assert.equal(all(root).filter(n=>n.id===id).length,1,id);assert.equal(document.getElementById('status').parentNode.attrs.class,'guide-banner');assert.equal(document.getElementById('duplicate').parentNode.id,'object-config');assert.equal(document.getElementById('exclusive-tap').hidden,true);assert.equal(document.getElementById('move').parentNode.attrs.class,'inspector-tools');assert.equal(document.getElementById('preview').parentNode.attrs.class,'preview-tools');assert.equal(document.getElementById('scale-chain').parentNode.id,'transform');assert.equal(document.getElementById('tap-next').closest('fieldset').attrs.class,'scene-switch-card');for(let step=0;step<3;step++){vm.runInContext('goStep('+step+')',context);const visible=document.querySelectorAll('[data-panel]').filter(n=>!n.hidden);assert.deepEqual(visible.map(n=>n.dataset.panel),step===0?['0']:step===1?['1','2']:['3','4','5']);if(step===1){assert.equal(document.getElementById('object-config').hidden,false);assert.equal(document.getElementById('reaction-config').hidden,false);}if(step===0)assert.equal(document.getElementById('scene-select').closest('section').dataset.panel,'0');}assert.equal(document.getElementById('publish-config').hidden,false);});
