import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createPairScene,compileMarkerSet,markerStates,trackingSummary} from '../studio/multi-marker.js';
import {validateScene,requiredAssets,validatePackage} from '../studio/schema.js';
import {Behavior} from '../studio/behavior.js';
const base=JSON.parse(await readFile(new URL('../public/scenes/demo-interactive/scene.json',import.meta.url)));
const second={id:'marker-2',name:'Marker B',image:'second.jpg',aspect:1,targetIndex:1};
const build=p=>createPairScene(p,{sourceSceneId:p.scenes[0].id,sourceMarkerId:p.markers[0].id,targetMarker:second});
function paired(){const p=structuredClone(base),s=build(p);p.markers.push(second);p.trackingTarget='combined.mind';p.maxTrack=2;p.scenes.push(s);p.initialSceneId=s.id;return{p,s};}
test('pair scene makes independent three-format artwork sets, preserves source and sound settings, clears scene transitions',()=>{const p=structuredClone(base),original=structuredClone(p),s=build(p);assert.deepEqual(p,original);assert.equal(s.objects.length,6);assert.deepEqual(s.objects.filter(o=>o.markerId===second.id).map(o=>o.kind).sort(),['glb','sprite','video']);for(const o of s.objects){assert.equal(o.interaction.nextSceneId,null);assert.equal(o.interaction.soundId,'tap-sound');}assert.equal(new Set(s.objects.map(o=>o.id)).size,6);s.objects[0].position[0]=99;assert.deepEqual(p,original);const built=paired();validateScene(built.p);const names=requiredAssets(built.p);assert.ok(names.includes('combined.mind'));assert.ok(names.includes('second.jpg'));const files=names.map(name=>({name,content:'eA=='}));validatePackage(built.p,files);assert.throws(()=>validatePackage(built.p,files.filter(f=>f.name!=='second.jpg')),/不足/);});
test('pair creation refuses missing source, reused marker, crowded scene and project limits',()=>{const empty=structuredClone(base);empty.scenes[0].objects=[];assert.throws(()=>build(empty),/作品/);const many=structuredClone(base);many.scenes[0].objects=Array.from({length:13},(_,i)=>({...many.scenes[0].objects[0],id:'old-'+i}));assert.throws(()=>build(many),/12作品/);const markers=structuredClone(base);markers.markers.push(second);assert.throws(()=>build(markers),/マーカー1枚/);const scenes=structuredClone(base);scenes.scenes=Array.from({length:12},(_,i)=>({...scenes.scenes[0],id:'scene-'+i}));assert.throws(()=>build(scenes),/上限/);const p=structuredClone(base);assert.throws(()=>createPairScene(p,{sourceSceneId:p.scenes[0].id,sourceMarkerId:p.markers[0].id,targetMarker:{...second,targetIndex:0}}),/不正/);});
test('all marker images compile in stable order into one shared target, export follows compilation',async()=>{const trace=[],compiler={async compileImageTargets(images,progress){trace.push(images);progress(100);return[{},{}];},async exportData(){trace.push('export');return new Uint8Array([1,2,3]);}};const output=await compileMarkerSet(['A','B'],{decode:async x=>'image-'+x,compiler,onProgress:p=>trace.push(p)});assert.deepEqual(trace,[['image-A','image-B'],100,'export']);assert.deepEqual([...output],[1,2,3]);await assert.rejects(compileMarkerSet(['A','B'],{decode:async x=>x,compiler:{compileImageTargets:async()=>[],exportData:async()=>new Uint8Array([1])}}),/生成できません/);});
test('losing marker A pauses only A while B remains active and tracker count changes from two to one',()=>{const{p,s}=paired(),visible=new Set([p.markers[0].id,second.id]);assert.equal(trackingSummary(p,s.id,visible).count,2);visible.delete(p.markers[0].id);const states=markerStates(p,s.id,visible);for(const o of s.objects){assert.equal(states.get(o.id).active,true);assert.equal(states.get(o.id).gate,o.markerId===second.id);}for(const o of p.scenes[0].objects)assert.deepEqual(states.get(o.id),{active:false,gate:false});assert.deepEqual(trackingSummary(p,s.id,visible),{count:1,limit:2,names:['Marker B']});visible.add(p.markers[0].id);assert.ok(s.objects.every(o=>markerStates(p,s.id,visible).get(o.id).gate));});
test('both marker objects respond in the same scene without switching away; old scene objects cannot trigger',()=>{const{p,s}=paired(),taps=[],b=new Behavior(p,{tap:o=>taps.push(o.markerId)});b.enter(s.id);b.running=true;const a=s.objects.find(o=>o.markerId===p.markers[0].id),c=s.objects.find(o=>o.markerId===second.id);assert.equal(b.tap(a.id),true);assert.equal(b.tap(c.id),true);assert.equal(b.tap(p.scenes[0].objects[0].id),false);b.update(10);assert.equal(b.scene.id,s.id);assert.deepEqual(taps,[p.markers[0].id,second.id]);});
