import test from 'node:test';import assert from 'node:assert/strict';import {createMarkerShadowRig,fitMarkerShadowRig,patchPackedAlphaDepth,shadowSettings,shadowLightPosition,shadowBounds} from '../studio/shadow-rig.js';import {readFile} from 'node:fs/promises';import {validateScene} from '../studio/schema.js';
class Object3D{constructor(){this.position={set:(...v)=>this.coordinates=v};this.children=[];this.userData={};}add(...items){this.children.push(...items);for(const i of items)i.parent=this;}}
class DirectionalLight extends Object3D{constructor(){super();this.shadow={mapSize:{set:(...v)=>this.resolution=v},camera:{updateProjectionMatrix:()=>this.updated=true}};}}
class Mesh extends Object3D{constructor(geometry,material){super();this.geometry=geometry;this.material=material;}}
class PlaneGeometry{constructor(...size){this.size=size;}}
class ShadowMaterial{constructor(options){Object.assign(this,options);}}
test('AR light, light target and receiver share marker parent and bounded local shadow camera independent of camera distance',()=>{const THREE={Object3D,DirectionalLight,Mesh,PlaneGeometry,ShadowMaterial,DoubleSide:2};const marker=new Object3D();marker.position.set(0,0,-40);const rig=createMarkerShadowRig(THREE,marker,1.5,.4);assert.equal(rig.light.parent,marker);assert.equal(rig.target.parent,marker);assert.equal(rig.light.target,rig.target);assert.equal(rig.receiver.parent,marker);assert.equal(rig.receiver.receiveShadow,true);assert.equal(rig.light.shadow.camera.far,16);assert.equal(rig.receiver.material.opacity,.4);assert.equal(rig.receiver.material.side,2);assert.equal(rig.light.updated,true);});
test('packed-alpha depth uses right-half grayscale mask, never the left color half',()=>{const shader={fragmentShader:'void main(){\n#include <map_fragment>\n#include <alphatest_fragment>\n}'};patchPackedAlphaDepth(shader);assert.match(shader.fragmentShader,/0.5\+vMapUv.x\*0.5/);assert.match(shader.fragmentShader,/\.r/);assert.ok(shader.fragmentShader.indexOf('texture2D')<shader.fragmentShader.indexOf('alphatest'));assert.throws(()=>patchPackedAlphaDepth({fragmentShader:'bad'}),/incompatible/);});
test('GLB, transparent video and sprite shadow flags save and validate without altering source format',async()=>{const p=JSON.parse(await readFile(new URL('../public/scenes/demo-interactive/scene.json',import.meta.url)));const objects=p.scenes[0].objects;assert.deepEqual(objects.map(o=>o.kind).sort(),['glb','sprite','video']);for(const o of objects)o.shadow=true;validateScene(p);assert.ok(JSON.parse(JSON.stringify(p)).scenes[0].objects.every(o=>o.shadow));});

test('shadow frustum follows large AR anchor scale rather than retaining editor-scale bounds',()=>{const THREE={Object3D,DirectionalLight,Mesh,PlaneGeometry,ShadowMaterial,DoubleSide:2,Vector3:class{}};const group=new Object3D();group.updateMatrixWorld=()=>{};group.getWorldScale=()=>({x:800,y:800,z:800});const rig=createMarkerShadowRig(THREE,group,1);fitMarkerShadowRig(rig,THREE);assert.equal(rig.light.shadow.camera.far,12800);assert.equal(rig.light.shadow.camera.right,3200);assert.equal(rig.light.shadow.normalBias,1.6);});

test('default shadow points beyond marker top and receiver spans four marker widths',()=>{const T={Object3D,DirectionalLight,Mesh,PlaneGeometry,ShadowMaterial,DoubleSide:2};const r=createMarkerShadowRig(T,new Object3D(),1.5);assert.deepEqual(r.light.coordinates,[0,-2,3]);assert.deepEqual(r.receiver.geometry.size,[4,6]);assert.deepEqual(shadowSettings(),{direction:'back',extent:4});});
test('all four directions and extended receiver bounds are shared settings',()=>{assert.deepEqual(shadowLightPosition('front'),[0,2,3]);assert.deepEqual(shadowLightPosition('left'),[2,0,3]);assert.deepEqual(shadowLightPosition('right'),[-2,0,3]);const T={Object3D,DirectionalLight,Mesh,PlaneGeometry,ShadowMaterial,DoubleSide:2};const r=createMarkerShadowRig(T,new Object3D(),2,.3,{shadowDirection:'left',shadowExtent:8});assert.deepEqual(r.receiver.geometry.size,[8,16]);assert.equal(r.bound,9);assert.equal(r.light.shadow.camera.right,9);assert.equal(shadowBounds(2,8),9);});
test('shadow direction and range persist and reject invalid settings',async()=>{const p=JSON.parse(await readFile(new URL('../public/scenes/demo-interactive/scene.json',import.meta.url)));p.shadowDirection='back';p.shadowExtent=4;validateScene(p);validateScene(JSON.parse(JSON.stringify(p)));p.shadowDirection='invalid';assert.throws(()=>validateScene(p),/影の方向/);p.shadowDirection='left';for(const n of [0,9,NaN]){p.shadowExtent=n;assert.throws(()=>validateScene(p),/影の範囲/);}});
