import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {Compiler} from 'mind-ar/src/image-target/compiler.js';
import JSZip from 'jszip';
import QRCode from 'qrcode';
import {MediaScene} from './media.js';
import {spriteSpec,validateScene,validatePackage,MAX_ASSET_BYTES,MAX_TOTAL_BYTES,sceneId} from './schema.js';
const $=id=>document.getElementById(id), status=text=>$('status').textContent=text;
const assets=new Map(), urls=new Map();let selected=null,markerMesh=null,session=null,busy=false,publishedURL='';
let scene={version:1,id:'art-001',title:'WebAR Art',revision:'draft',marker:null,objects:[]};
const view=$('viewport'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.prepend(renderer.domElement);
const world=new THREE.Scene();world.background=new THREE.Color('#1b2b30');const camera=new THREE.PerspectiveCamera(45,1,.01,100);camera.position.set(0,1.3,3.5);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,0,0);orbit.update();
const gizmo=new TransformControls(camera,renderer.domElement);gizmo.setSpace('local');world.add(gizmo);gizmo.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);
world.add(new THREE.HemisphereLight(0xffffff,0x4f6870,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(2,3,4);world.add(light);
const grid=new THREE.GridHelper(4,16,0x577a79,0x344d52);grid.rotation.x=Math.PI/2;grid.position.z=-.015;world.add(grid);
const media=new MediaScene(name=>{if(!urls.has(name))throw new Error('素材がありません: '+name);return urls.get(name);},new URL('./',location.href));world.add(media.root);
const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{media.update(Math.min(clock.getDelta(),.05));renderer.render(world,camera);});
new ResizeObserver(()=>{const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(view);
const fields={};for(const [key,label] of [['position','位置 XYZ'],['rotation','回転 XYZ（度）'],['scale','サイズ XYZ']]){const l=document.createElement('label');l.textContent=label;$('transform').append(l);const row=document.createElement('div');row.className='grid3';fields[key]=[];for(let i=0;i<3;i++){const input=document.createElement('input');input.type='number';input.step=key==='rotation'?'1':'.01';input.disabled=true;input.setAttribute('aria-label',label+' '+['X','Y','Z'][i]);input.onchange=()=>{if(!selected)return;const value=Number(input.value);if(!Number.isFinite(value)||Math.abs(value)>100||(key==='scale'&&value<=0)){status('値の範囲を確認してください。');syncFields();return;}selected[key][i]=value;media.apply(selected);saveDraft();};fields[key].push(input);row.append(input);}$('transform').append(row);}
function syncFields(){for(const key of Object.keys(fields))fields[key].forEach((input,i)=>{input.disabled=!selected;input.value=selected?Number(selected[key][i].toFixed(3)):'';});$('name').disabled=!selected;$('name').value=selected?.name||'';$('fps').disabled=selected?.kind!=='sprite';$('fps').value=selected?.sprite?.fps||'';}
function choose(id){selected=scene.objects.find(o=>o.id===id)||null;if(selected)gizmo.attach(media.items.get(id).group);else gizmo.detach();syncFields();list();}
function list(){$('objects').replaceChildren();for(const object of scene.objects){const b=document.createElement('button');b.textContent=object.name+' / '+object.kind;b.className=object===selected?'selected':'';b.onclick=()=>choose(object.id);$('objects').append(b);}}
gizmo.addEventListener('objectChange',()=>{if(!selected)return;const g=media.items.get(selected.id).group;selected.position=g.position.toArray();selected.rotation=[g.rotation.x,g.rotation.y,g.rotation.z].map(THREE.MathUtils.radToDeg);selected.scale=g.scale.toArray();syncFields();});gizmo.addEventListener('mouseUp',saveDraft);
const ray=new THREE.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(gizmo.dragging||gizmo.axis||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);const hit=ray.intersectObjects(media.root.children,true)[0];if(hit){for(const [id,item]of media.items)if(item.group===hit.object||isChild(hit.object,item.group)){choose(id);break;}}});
function isChild(object,parent){for(let x=object;x;x=x.parent)if(x===parent)return true;return false;}
for(const [id,mode]of [['move','translate'],['rotate','rotate'],['scale','scale']])$(id).onclick=()=>gizmo.setMode(mode);
$('name').onchange=()=>{if(selected){selected.name=$('name').value.slice(0,100);list();saveDraft();}};
$('fps').onchange=()=>{if(selected?.kind==='sprite'){const n=Number($('fps').value);if(n>=1&&n<=60){selected.sprite.fps=n;saveDraft();}else syncFields();}};
$('delete').onclick=()=>{if(!selected)return;const id=selected.id;gizmo.detach();media.remove(id);scene.objects=scene.objects.filter(o=>o.id!==id);choose(null);saveDraft();};
$('duplicate').onclick=()=>task(async()=>{if(!selected)return;const spec=structuredClone(selected);spec.id=crypto.randomUUID();spec.name+=' copy';spec.position[0]+=.1;await addObject(spec);saveDraft();});
$('preview').onclick=()=>{if(media.playing)media.pause();else media.play().then(r=>{if(r.some(x=>x.status==='rejected'))status('動画を再生できません。再生ボタンをもう一度押してください。');});};
function put(name,blob){if(blob.size>MAX_ASSET_BYTES)throw new Error('素材は24MB以内です。');assets.set(name,blob);if(urls.has(name))URL.revokeObjectURL(urls.get(name));urls.set(name,URL.createObjectURL(blob));}
async function addObject(spec){if(scene.objects.length>=24)throw new Error('作品は24個までです。');await media.add(spec);scene.objects.push(spec);choose(spec.id);}
function object(kind,src,name,extra={}){return{id:crypto.randomUUID(),kind,src,name:name.slice(0,100),position:[0,0,.1],rotation:[0,0,0],scale:[.5,.5,.5],...extra};}
async function imageFrom(blob){const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();return image;}finally{URL.revokeObjectURL(url);}}
async function showMarker(){if(markerMesh){world.remove(markerMesh);markerMesh.geometry.dispose();markerMesh.material.map.dispose();markerMesh.material.dispose();}if(!scene.marker)return;const texture=await new THREE.TextureLoader().loadAsync(urls.get(scene.marker.image));texture.colorSpace=THREE.SRGBColorSpace;markerMesh=new THREE.Mesh(new THREE.PlaneGeometry(1,scene.marker.aspect),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));world.add(markerMesh);}
$('marker').onchange=()=>task(async()=>{const file=$('marker').files[0];if(!file)return;if(file.size>MAX_ASSET_BYTES)throw new Error('マーカー画像は24MB以内です。');const image=await imageFrom(file);if(image.width<200||image.height<200)throw new Error('マーカーは200px以上の画像を使用してください。');const canvas=document.createElement('canvas');const factor=Math.min(1,1600/Math.max(image.width,image.height));canvas.width=Math.round(image.width*factor);canvas.height=Math.round(image.height*factor);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.94));const trackingImage=await imageFrom(blob);const compiler=new Compiler();const data=await compiler.compileImageTargets([trackingImage],p=>status('マーカー認識データ生成中 '+Math.round(p)+'%'));if(!data?.length)throw new Error('認識データを生成できません。');const id=crypto.randomUUID();put(id+'.jpg',blob);put(id+'.mind',new Blob([await compiler.exportData()]));scene.marker={image:id+'.jpg',target:id+'.mind',aspect:canvas.height/canvas.width};await showMarker();await saveDraft();status('マーカーを登録しました。作品を追加してください。');});
$('print').onclick=()=>{if(!scene.marker)return status('先にマーカーを登録してください。');const w=window.open('','_blank');if(!w)return status('ポップアップを許可してください。');w.document.title='WebAR Art マーカー';const img=w.document.createElement('img');img.src=urls.get(scene.marker.image);img.style.cssText='display:block;width:90%;max-width:1000px;margin:auto';w.document.body.append(img);const b=w.document.createElement('button');b.textContent='印刷';b.onclick=()=>w.print();w.document.body.prepend(b);};
async function importSprite(file){const zip=await JSZip.loadAsync(file);const entries=Object.values(zip.files).filter(f=>!f.dir&&!f.name.startsWith('__MACOSX/'));const jsons=entries.filter(f=>/\.(json|sprite)$/i.test(f.name));let meta,entry;for(const j of jsons){const s=await j.async('string');if(s.length>100000)continue;try{const d=JSON.parse(s);if(d.type==='sprite-sheet'){meta=d;entry=j;break;}}catch{}}if(!meta)throw new Error('sprite-sheetのJSONが見つかりません。');const spec=spriteSpec(meta);const dir=entry.name.slice(0,entry.name.lastIndexOf('/')+1);if(typeof meta.image!=='string'||meta.image.includes('..')||meta.image.startsWith('/'))throw new Error('Sprite画像パスが不正です。');const imgEntry=zip.file(dir+meta.image);if(!imgEntry)throw new Error('Sprite画像がありません。');const bytes=await imgEntry.async('uint8array');if(bytes.length>MAX_ASSET_BYTES)throw new Error('Sprite画像が大きすぎます。');const image=await imageFrom(new Blob([bytes]));if(image.width!==spec.columns*spec.frameWidth||image.height!==spec.rows*spec.frameHeight)throw new Error('SpriteのJSONと画像サイズが一致しません。');const ratio=Math.min(1,4096/Math.max(image.width,image.height));const fw=Math.max(1,Math.floor(spec.frameWidth*ratio)),fh=Math.max(1,Math.floor(spec.frameHeight*ratio));const canvas=document.createElement('canvas');canvas.width=fw*spec.columns;canvas.height=fh*spec.rows;canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));const name=crypto.randomUUID()+'.png';put(name,blob);return object('sprite',name,file.name,{sprite:{...spec,frameWidth:fw,frameHeight:fh}});}
$('asset').onchange=()=>task(async()=>{const file=$('asset').files[0];if(!file)return;if(file.size>MAX_ASSET_BYTES)throw new Error('ファイルは24MB以内です。');const extension=file.name.split('.').pop().toLowerCase();let spec;
 if(extension==='glb'){const header=new Uint8Array(await file.slice(0,4).arrayBuffer());if(String.fromCharCode(...header)!=='glTF')throw new Error('GLBファイルではありません。');const name=crypto.randomUUID()+'.glb';put(name,file);spec=object('glb',name,file.name);}
 else if(['zip','sprite'].includes(extension)){spec=await importSprite(file);}
 else if(['webm','mp4'].includes(extension)){if(!session?.canConvert)throw new Error('動画の追加は公開サーバーのStudioで行ってください。');status('動画をSafari用に変換中…');const response=await fetch('/api/video?format='+extension,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-CSRF-Token':session.csrf||''},body:file});if(!response.ok)throw new Error((await response.json()).error||'動画変換に失敗');const result=await response.json();const name=crypto.randomUUID()+'.'+extension,fallback=crypto.randomUUID()+'.mp4';put(name,file);put(fallback,decodeBlob(result.content,'video/mp4'));spec=object('video',name,file.name,{fallback:{src:fallback,packedAlpha:result.packedAlpha},loop:true});}
 else throw new Error('GLB、WebM、MP4、Sprite ZIPに対応しています。');
 await addObject(spec);await saveDraft();media.play();status('作品を追加しました。XYZを編集するか、3D画面のハンドルをドラッグしてください。');});
function decodeBlob(content,type){const raw=atob(content);return new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type});}
async function encodeBlob(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});}
function selectedAssets(){const names=new Set([scene.marker?.image,scene.marker?.target]);scene.objects.forEach(o=>{names.add(o.src);if(o.fallback)names.add(o.fallback.src);});return [...names].filter(Boolean);}
async function snapshot(){scene.id=$('scene-id').value;scene.title=$('title').value;scene.revision=crypto.randomUUID();validateScene(scene);const files=[];for(const name of selectedAssets()){const blob=assets.get(name);if(!blob)throw new Error('素材が不足: '+name);files.push({name,content:await encodeBlob(blob)});}return validatePackage(structuredClone(scene),files);}
async function loadData(data){validatePackage(data.scene,data.files);gizmo.detach();media.dispose();media.draco=new (await import('three/addons/loaders/DRACOLoader.js')).DRACOLoader();media.draco.setDecoderPath(new URL('./vendor/three/draco/',location.href).href);media.loader.setDRACOLoader(media.draco);for(const url of urls.values())URL.revokeObjectURL(url);assets.clear();urls.clear();for(const file of data.files)put(file.name,decodeBlob(file.content,''));scene=structuredClone(data.scene);const objects=scene.objects;scene.objects=[];selected=null;$('scene-id').value=scene.id;$('title').value=scene.title;await showMarker();for(const o of objects)await addObject(o);media.time=0;await media.play();choose(null);}
async function loadPublished(id,base=new URL('./',location.href)){if(!sceneId(id))throw new Error('体験IDは半角小文字・数字・ハイフンで指定してください。');const dir=new URL('scenes/'+id+'/',base);const r=await fetch(new URL('scene.json',dir),{cache:'no-store'});if(!r.ok)throw new Error('シーンが見つかりません。');const s=validateScene(await r.json());const names=new Set([s.marker.image,s.marker.target]);s.objects.forEach(o=>{names.add(o.src);if(o.fallback)names.add(o.fallback.src);});const files=[];for(const name of names){const r=await fetch(new URL(name,dir));if(!r.ok)throw new Error('素材を取得できません: '+name);const blob=await r.blob();if(blob.size>MAX_ASSET_BYTES)throw new Error('素材サイズ超過');files.push({name,content:await encodeBlob(blob)});}await loadData({scene:s,files});await saveDraft();status('シーンを読み込みました。');}
$('sample').onclick=()=>task(()=>loadPublished('demo'));
$('scene-id').onchange=()=>{if(sceneId($('scene-id').value)){scene.id=$('scene-id').value;saveDraft();}else status('体験IDは半角小文字・数字・ハイフンで指定してください。');};
$('title').onchange=()=>{scene.title=$('title').value.slice(0,100);saveDraft();};
$('reload').onclick=()=>task(()=>loadPublished($('scene-id').value,new URL(session?.pagesURL||'./',location.href)));
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);}
$('save').onclick=()=>task(async()=>{const data=await snapshot();const zip=new JSZip();zip.file('scene.json',JSON.stringify(data.scene,null,2));for(const f of data.files)zip.file(f.name,f.content,{base64:true});download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),scene.id+'-project.zip');status('制作データを保存しました。');});
$('restore').onchange=()=>task(async()=>{const file=$('restore').files[0];if(!file)return;if(file.size>MAX_TOTAL_BYTES)throw new Error('ZIPは48MB以内です。');const zip=await JSZip.loadAsync(file);if(!zip.file('scene.json'))throw new Error('制作ZIPではありません。');const text=await zip.file('scene.json').async('string');if(text.length>1000000)throw new Error('シーンデータが大きすぎます。');const s=validateScene(JSON.parse(text));const names=new Set([s.marker.image,s.marker.target]);s.objects.forEach(o=>{names.add(o.src);if(o.fallback)names.add(o.fallback.src);});const files=[];for(const name of names){const entry=zip.file(name);if(!entry)throw new Error('素材が不足: '+name);const content=await entry.async('base64');if(content.length>MAX_ASSET_BYTES*4/3)throw new Error('素材サイズ超過');files.push({name,content});}await loadData({scene:s,files});await saveDraft();status('制作データを復元しました。');});
async function task(fn){if(busy)return;busy=true;const disabled=[...document.querySelectorAll('button,input[type=file]')];disabled.forEach(e=>e.disabled=true);try{await fn();}catch(e){status('処理を止めました: '+e.message);}finally{busy=false;disabled.forEach(e=>e.disabled=false);syncFields();$('publish').disabled=!session?.authenticated;}}
$('logout').onclick=()=>task(async()=>{const r=await fetch('/api/logout',{method:'POST',headers:{'X-CSRF-Token':session.csrf}});if(!r.ok)throw new Error('接続終了に失敗しました。');location.reload();});
$('publish').onclick=()=>task(async()=>{
 if(!session?.authenticated)throw new Error('先にGitHubへ接続してください。');
 const data=await snapshot();$('qr').hidden=true;$('public-link').hidden=true;$('copy').hidden=true;$('save-qr').hidden=true;status('GitHubへ送信しています…');
 const r=await fetch('/api/publish',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:JSON.stringify({scene:data.scene,files:data.files})});const job=await r.json();if(!r.ok)throw new Error(job.error||'送信に失敗');
 sessionStorage.setItem('webar-publish-job',job.id);await watch(job.id);
});
async function watch(id){for(let i=0;i<120;i++){const r=await fetch('/api/jobs/'+encodeURIComponent(id));const job=await r.json();if(!r.ok)throw new Error(job.error||'公開状態を取得できません');status(job.message);if(job.state==='failed'){sessionStorage.removeItem('webar-publish-job');throw new Error(job.message);}if(job.state==='ready'){publishedURL=job.url;await QRCode.toCanvas($('qr'),job.url,{width:240,margin:2,errorCorrectionLevel:'M'});$('qr').hidden=false;$('public-link').href=job.url;$('public-link').textContent=job.url;$('public-link').hidden=false;$('copy').hidden=false;$('save-qr').hidden=false;sessionStorage.removeItem('webar-publish-job');return;}await new Promise(r=>setTimeout(r,5000));}throw new Error('公開確認が継続中です。画面を再読込すると確認を再開します。');}
$('copy').onclick=()=>navigator.clipboard.writeText(publishedURL).then(()=>status('URLをコピーしました。')).catch(()=>status('表示されたURLをコピーしてください。'));
$('save-qr').onclick=()=>$('qr').toBlob(blob=>download(blob,scene.id+'-qr.png'));
const dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('webar-art-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('draft');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
let saveTimer;async function saveDraft(){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const db=await dbPromise;const tx=db.transaction('draft','readwrite');tx.objectStore('draft').put({scene:structuredClone(scene),files:[...assets].map(([name,blob])=>({name,blob}))},'current');tx.onerror=()=>status('自動保存できません。制作データ保存を使用してください。');}catch{status('自動保存を利用できません。制作データ保存を使用してください。');}},400);}
async function init(){try{const r=await fetch('/api/session');if(r.ok)session=await r.json();}catch{}
 $('publish').disabled=!session?.authenticated;$('login').hidden=!session?.oauthAvailable||session?.authenticated;$('logout').hidden=!session?.authenticated;$('connection').textContent=session?.authenticated?'GitHub接続済み: '+session.login+' → '+session.repository:session?.canConvert?'ローカル編集。直接公開にはGitHub接続が必要です。':'GitHub Pages上の編集。直接公開は公開サーバーで行ってください。';
 try{const db=await dbPromise;const data=await new Promise((resolve,reject)=>{const req=db.transaction('draft').objectStore('draft').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(data?.scene?.marker&&data.scene.objects.length){const files=[];for(const f of data.files)files.push({name:f.name,content:await encodeBlob(f.blob)});await loadData({scene:data.scene,files});status('前回の制作データを復元しました。');}else await loadPublished('demo');}catch(e){status('マーカー画像と作品を登録してください。'+e.message);}
 const job=sessionStorage.getItem('webar-publish-job');if(job&&session?.authenticated)task(()=>watch(job));
}
init();
