import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {Compiler} from 'mind-ar/src/image-target/compiler.js';
import JSZip from 'jszip';
import QRCode from 'qrcode';
import {MediaScene} from './media.js';
import {AudioBank} from './audio.js';
import {Behavior} from './behavior.js';
import {configureShadowLight,shadowSettings,shadowLightPosition,shadowBounds} from './shadow-rig.js';
import {scaleAxis,tapEnabled} from './object-controls.js';
import {STEPS,WORKSPACES,reactionText,exclusiveReaction,publicURL} from './workflow.js';
import {createPairScene,compileMarkerSet} from './multi-marker.js';
import {spriteSpec,validateScene,validatePackage,MAX_ASSET_BYTES,MAX_TOTAL_BYTES,sceneId,toProject,requiredAssets,defaultInteraction} from './schema.js';
const $=id=>document.getElementById(id), status=text=>{$('status').textContent=text;};
let savedFingerprint='',publishedFingerprint='',activeStep=0;
const assets=new Map(), urls=new Map();let selected=null,markerMesh=null,shadowPlane=null,session=null,busy=false,publishedURL='';
let project={version:2,id:'art-001',title:'WebAR Art',revision:'draft',trackingTarget:'pending.mind',maxTrack:1,markers:[],sounds:[],initialSceneId:'scene-1',scenes:[{id:'scene-1',name:'シーン1',autoNextSeconds:0,nextSceneId:null,markerLost:'continue',objects:[]}]};
let scene=project.scenes[0],markerId=null,previewing=false,behavior=null;const audio=new AudioBank(name=>urls.get(name));
const marker=()=>project.markers.find(m=>m.id===markerId);
const view=$('viewport'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.prepend(renderer.domElement);
const world=new THREE.Scene();world.background=new THREE.Color('#1b2b30');const camera=new THREE.PerspectiveCamera(45,1,.01,100);camera.position.set(0,1.3,3.5);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,0,0);orbit.update();
const gizmo=new TransformControls(camera,renderer.domElement);gizmo.setSpace('local');world.add(gizmo);gizmo.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);
world.add(new THREE.HemisphereLight(0xffffff,0x4f6870,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(2,3,4);world.add(light);
const grid=new THREE.GridHelper(4,16,0x577a79,0x344d52);grid.rotation.x=Math.PI/2;grid.position.z=-.015;world.add(grid);
const media=new MediaScene(name=>{if(!urls.has(name))throw new Error('素材がありません: '+name);return urls.get(name);},new URL('./',location.href));world.add(media.root);
const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(previewing)behavior?.update(dt);media.update(dt);renderer.render(world,camera);});
new ResizeObserver(()=>{const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(view);
const fields={};for(const [key,label] of [['position','位置 XYZ'],['rotation','回転 XYZ（度）'],['scale','サイズ XYZ']]){const l=document.createElement('label');l.textContent=label;$('transform').append(l);const row=document.createElement('div');row.className='grid3';fields[key]=[];for(let i=0;i<3;i++){const input=document.createElement('input');input.type='number';input.step=key==='rotation'?'1':'.01';input.disabled=true;input.setAttribute('aria-label',label+' '+['X','Y','Z'][i]);input.onchange=()=>{if(!selected)return;const value=Number(input.value);if(!Number.isFinite(value)||Math.abs(value)>100||(key==='scale'&&value<=0)){status('値の範囲を確認してください。');syncFields();return;}if(key==='scale'){try{selected.scale=scaleAxis(selected.scale,i,value,selected.scaleLinked!==false);}catch(e){status(e.message);syncFields();return;}}else selected[key][i]=value;syncFields();media.apply(selected);saveDraft();};fields[key].push(input);row.append(input);}$('transform').append(row);}
function syncFields(){if($('scale-chain')){$('scale-chain').disabled=!selected;$('scale-chain').textContent=selected?.scaleLinked===false?'⛓ 連動 OFF':'🔗 連動 ON';$('scale-chain').setAttribute('aria-pressed',String(selected?.scaleLinked!==false));$('shadow-on').disabled=!selected;$('shadow-on').checked=selected?.shadow===true;$('shadow-opacity').value=Math.round((project.shadowOpacity??.3)*100);$('shadow-direction').value=shadowSettings(project).direction;$('shadow-extent').value=shadowSettings(project).extent;$('scene-switch-on').disabled=!selected;$('scene-switch-on').checked=!!selected?.interaction.nextSceneId;$('tap-next').disabled=!selected||!selected.interaction.nextSceneId;}if($('opacity')){$('opacity').disabled=!selected;$('opacity').value=Math.round((selected?.opacity??1)*100);$('opacity-value').textContent=$('opacity').value+'%';}for(const key of Object.keys(fields))fields[key].forEach((input,i)=>{input.disabled=!selected;input.value=selected?Number(selected[key][i].toFixed(3)):'';});$('name').disabled=!selected;$('name').value=selected?.name||'';$('fps').disabled=selected?.kind!=='sprite';$('fps').value=selected?.sprite?.fps||'';syncInteraction();if($('scene-switch-on'))$('tap-next').disabled=!selected||!selected.interaction.nextSceneId;}
function choose(id){selected=scene.objects.find(o=>o.id===id)||null;if(selected&&!previewing)gizmo.attach(media.items.get(id).group);else gizmo.detach();syncFields();list();updateGuide();}
function list(){$('objects').replaceChildren();for(const object of scene.objects.filter(o=>o.markerId===markerId)){const row=document.createElement('div');row.className='object-row';const b=document.createElement('button');b.textContent=object.name+' / '+object.kind;b.className=object===selected?'selected':'';b.onclick=()=>choose(object.id);const toggle=document.createElement('button');toggle.textContent=tapEnabled(object)?'タップ ON':'タップ OFF';toggle.className='tap-switch';toggle.setAttribute('aria-pressed',String(tapEnabled(object)));toggle.setAttribute('aria-label',object.name+'のタップ反応');toggle.onclick=()=>{object.tapEnabled=!tapEnabled(object);if(!object.tapEnabled)audio.stop(object.id);saveDraft();list();syncFields();};row.append(b,toggle);$('objects').append(row);}}

gizmo.addEventListener('objectChange',()=>{if(!selected)return;const g=media.items.get(selected.id).group;selected.position=g.position.toArray();selected.rotation=[g.rotation.x,g.rotation.y,g.rotation.z].map(THREE.MathUtils.radToDeg);if(selected.scaleLinked!==false&&gizmo.getMode()==='scale'){const scale=g.scale.toArray(),previous=selected.scale;const changes=scale.map((v,i)=>Math.abs(v/previous[i]-1));const axis=['X','Y','Z'].includes(gizmo.axis)?['X','Y','Z'].indexOf(gizmo.axis):changes.indexOf(Math.max(...changes));try{selected.scale=scaleAxis(previous,axis,scale[axis],true);g.scale.fromArray(selected.scale);}catch(e){g.scale.fromArray(previous);status(e.message);}}else selected.scale=g.scale.toArray();syncFields();});gizmo.addEventListener('mouseUp',saveDraft);
const ray=new THREE.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(gizmo.dragging||gizmo.axis||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);const hit=ray.intersectObjects([...media.items.values()].filter(i=>i.group.visible).map(i=>i.group),true)[0];if(hit){for(const [id,item]of media.items)if(item.group===hit.object||isChild(hit.object,item.group)){if(previewing){audio.unlock().catch(e=>status(e.message));try{behavior.tap(id);}catch(e){status(e.message);}}else choose(id);break;}}});
function isChild(object,parent){for(let x=object;x;x=x.parent)if(x===parent)return true;return false;}
for(const [id,mode]of [['move','translate'],['rotate','rotate'],['scale','scale']])$(id).onclick=()=>gizmo.setMode(mode);
$('name').onchange=()=>{if(selected){selected.name=$('name').value.slice(0,100);list();saveDraft();}};
$('fps').onchange=()=>{if(selected?.kind==='sprite'){const n=Number($('fps').value);if(n>=1&&n<=60){selected.sprite.fps=n;saveDraft();}else syncFields();}};
$('delete').onclick=()=>{if(!selected)return;const id=selected.id;gizmo.detach();audio.stop(id);media.remove(id);scene.objects=scene.objects.filter(o=>o.id!==id);choose(null);saveDraft();};
$('duplicate').onclick=()=>task(async()=>{if(!selected)return;const spec=structuredClone(selected);spec.id=crypto.randomUUID();spec.name+=' copy';spec.position[0]+=.1;await addObject(spec);saveDraft();});
$('preview').onclick=()=>task(async()=>{if(previewing){endPreview();status('編集へ戻りました。');}else{await audio.load(project.sounds);await audio.unlock();behavior=new Behavior(project,{leave:()=>audio.stopAll(),enter:s=>{scene=s;markerId=scene.objects[0]?.markerId||markerId;refresh();for(const o of scene.objects)media.reset(o.id);},tap:(o,playing)=>{if(o.interaction.action==='restart')media.restart(o.id).catch(e=>status(e.message));else if(o.interaction.action==='toggle')media.setPlaying(o.id,playing).catch(e=>status(e.message));media.effect(o.id);if(o.interaction.action!=='toggle'||playing)audio.play(o).catch(e=>status(e.message));else audio.stop(o.id);}});behavior.enter(scene.id);behavior.running=true;previewing=true;gizmo.detach();await media.play();status('プレビュー中：作品をクリックして反応を確認。マーカー切替で他の配置を表示できます。');}});
function endPreview(){media.pause();previewing=false;behavior?.stop();audio.stopAll();scene=project.scenes.find(s=>s.id===$('scene-select').value)||scene;refresh();}
function put(name,blob){if(blob.size>MAX_ASSET_BYTES)throw new Error('素材は24MB以内です。');assets.set(name,blob);if(urls.has(name))URL.revokeObjectURL(urls.get(name));urls.set(name,URL.createObjectURL(blob));}
async function addObject(spec){endPreview();if(!marker())throw new Error('先にマーカーを登録してください。');if(project.scenes.flatMap(s=>s.objects).length>=48)throw new Error('全体で48作品までです。');if(scene.objects.length>=24)throw new Error('作品は24個までです。');await media.add(spec);scene.objects.push(spec);media.setGate(spec.id,true);choose(spec.id);}
function object(kind,src,name,extra={}){return{scaleLinked:true,tapEnabled:true,shadow:false,id:crypto.randomUUID(),kind,src,name:name.slice(0,100),markerId,autoplay:true,interaction:defaultInteraction(),position:[0,0,.1],rotation:[0,0,0],scale:[.5,.5,.5],...extra};}
async function imageFrom(blob){const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();return image;}finally{URL.revokeObjectURL(url);}}
let markerRender=0;
async function showMarker(){if(shadowPlane){world.remove(shadowPlane);shadowPlane.geometry.dispose();shadowPlane.material.dispose();shadowPlane=null;}const generation=++markerRender;if(markerMesh){world.remove(markerMesh);markerMesh.geometry.dispose();markerMesh.material.map.dispose();markerMesh.material.dispose();markerMesh=null;}const m=marker();if(!m)return;const texture=await new THREE.TextureLoader().loadAsync(urls.get(m.image));if(generation!==markerRender){texture.dispose();return;}texture.colorSpace=THREE.SRGBColorSpace;markerMesh=new THREE.Mesh(new THREE.PlaneGeometry(1,m.aspect),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));world.add(markerMesh);shadowPlane=new THREE.Mesh(new THREE.PlaneGeometry(1,m.aspect),new THREE.ShadowMaterial({opacity:project.shadowOpacity??.3,depthWrite:false,side:THREE.DoubleSide}));shadowPlane.position.z=.002;shadowPlane.receiveShadow=true;shadowPlane.raycast=()=>{};world.add(shadowPlane);updateShadow();}
async function compileAdditionalMarker(file){
 if(project.markers.length>=8)throw new Error('マーカーは8枚までです。');if(file.size>MAX_ASSET_BYTES)throw new Error('画像は24MB以内です。');const image=await imageFrom(file);if(image.width<200||image.height<200)throw new Error('200px以上の画像を使用してください。');const canvas=document.createElement('canvas'),factor=Math.min(1,1600/Math.max(image.width,image.height));canvas.width=Math.round(image.width*factor);canvas.height=Math.round(image.height*factor);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.94));if(!blob)throw new Error('マーカー画像を作成できません。');const digest=b=>b.arrayBuffer().then(a=>crypto.subtle.digest('SHA-256',a)).then(a=>Array.from(new Uint8Array(a)).join(','));const hash=await digest(blob);for(const m of project.markers)if(await digest(assets.get(m.image))===hash)throw new Error('同じマーカー画像は登録済みです。異なる画像を選んでください。');const id=crypto.randomUUID(),name=id+'.jpg';const candidate={id,name:file.name.slice(0,100),image:name,aspect:canvas.height/canvas.width,targetIndex:project.markers.length};const bytes=await compileMarkerSet([...project.markers.map(m=>assets.get(m.image)),blob],{decode:imageFrom,compiler:new Compiler(),onProgress:p=>status('全マーカーの認識データ生成中 '+Math.round(p)+'%')});const target=crypto.randomUUID()+'.mind',trackingBlob=new Blob([bytes]);if(trackingBlob.size>MAX_ASSET_BYTES)throw new Error('認識データが24MBを超えています。');return{candidate,blob,target,trackingBlob};
}
function commitMarker(compiled){put(compiled.candidate.image,compiled.blob);put(compiled.target,compiled.trackingBlob);project.markers.push(compiled.candidate);project.trackingTarget=compiled.target;project.maxTrack=Math.min(2,project.markers.length);markerId=compiled.candidate.id;}
$('marker').onchange=()=>task(async()=>{endPreview();const file=$('marker').files[0];if(!file)return;commitMarker(await compileAdditionalMarker(file));await refresh();await saveDraft();status('マーカーを追加しました。選択中のマーカーに作品を追加してください。');});
$('pair-marker').onchange=()=>task(async()=>{
 endPreview();const file=$('pair-marker').files[0];if(!file)return;const sourceScene=scene,sourceMarker=markerId;
 // Check capacity before expensive browser compilation.
 createPairScene(project,{sourceSceneId:sourceScene.id,sourceMarkerId:sourceMarker,targetMarker:{id:'capacity-check',targetIndex:project.markers.length}});
 const compiled=await compileAdditionalMarker(file),paired=createPairScene(project,{sourceSceneId:sourceScene.id,sourceMarkerId:sourceMarker,targetMarker:compiled.candidate});
 const added=[];try{for(const o of paired.objects){await media.add(o);added.push(o.id);}}catch(e){for(const id of added)media.remove(id);throw e;}
 commitMarker(compiled);project.scenes.push(paired);project.initialSceneId=paired.id;scene=paired;markerId=sourceMarker;project.id='art-002';project.title='2マーカー同時表示';$('scene-id').value=project.id;$('title').value=project.title;await refresh();await saveDraft();status('2マーカーの同時表示シーンを作成しました。A・Bへ各'+(paired.objects.length/2)+'作品を配置しました。両マーカーを表示・印刷し、制作データ保存からart-002を公開してください。');
});
$('print-both').onclick=()=>{if(project.markers.length<2)return status('先に2枚のマーカーを登録してください。');const w=window.open('','_blank');if(!w)return status('ポップアップを許可してください。');w.document.title='WebAR Art マーカー一覧';const b=w.document.createElement('button');b.textContent='印刷';b.onclick=()=>w.print();w.document.body.append(b);for(const m of project.markers){const section=w.document.createElement('section');section.style.cssText='break-inside:avoid;margin:30px auto;max-width:600px';const label=w.document.createElement('h2');label.textContent=m.name;const img=w.document.createElement('img');img.src=urls.get(m.image);img.style.cssText='display:block;width:100%';section.append(label,img);w.document.body.append(section);}};
$('print').onclick=()=>{if(!marker())return status('先にマーカーを登録してください。');const w=window.open('','_blank');if(!w)return status('ポップアップを許可してください。');w.document.title='WebAR Art マーカー';const img=w.document.createElement('img');img.src=urls.get(marker().image);img.style.cssText='display:block;width:90%;max-width:1000px;margin:auto';w.document.body.append(img);const b=w.document.createElement('button');b.textContent='印刷';b.onclick=()=>w.print();w.document.body.prepend(b);};
async function importSprite(file){const zip=await JSZip.loadAsync(file);const entries=Object.values(zip.files).filter(f=>!f.dir&&!f.name.startsWith('__MACOSX/'));const jsons=entries.filter(f=>/\.(json|sprite)$/i.test(f.name));let meta,entry;for(const j of jsons){const s=await j.async('string');if(s.length>100000)continue;try{const d=JSON.parse(s);if(d.type==='sprite-sheet'){meta=d;entry=j;break;}}catch{}}if(!meta)throw new Error('sprite-sheetのJSONが見つかりません。');const spec=spriteSpec(meta);const dir=entry.name.slice(0,entry.name.lastIndexOf('/')+1);if(typeof meta.image!=='string'||meta.image.includes('..')||meta.image.startsWith('/'))throw new Error('Sprite画像パスが不正です。');const imgEntry=zip.file(dir+meta.image);if(!imgEntry)throw new Error('Sprite画像がありません。');const bytes=await imgEntry.async('uint8array');if(bytes.length>MAX_ASSET_BYTES)throw new Error('Sprite画像が大きすぎます。');const image=await imageFrom(new Blob([bytes]));if(image.width!==spec.columns*spec.frameWidth||image.height!==spec.rows*spec.frameHeight)throw new Error('SpriteのJSONと画像サイズが一致しません。');const ratio=Math.min(1,4096/Math.max(image.width,image.height));const fw=Math.max(1,Math.floor(spec.frameWidth*ratio)),fh=Math.max(1,Math.floor(spec.frameHeight*ratio));const canvas=document.createElement('canvas');canvas.width=fw*spec.columns;canvas.height=fh*spec.rows;canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));const name=crypto.randomUUID()+'.png';put(name,blob);return object('sprite',name,file.name,{sprite:{...spec,frameWidth:fw,frameHeight:fh}});}
$('asset').onchange=()=>task(async()=>{const file=$('asset').files[0];if(!file)return;if(file.size>MAX_ASSET_BYTES)throw new Error('ファイルは24MB以内です。');const extension=file.name.split('.').pop().toLowerCase();let spec;
 if(extension==='glb'){const header=new Uint8Array(await file.slice(0,4).arrayBuffer());if(String.fromCharCode(...header)!=='glTF')throw new Error('GLBファイルではありません。');const name=crypto.randomUUID()+'.glb';put(name,file);spec=object('glb',name,file.name);}
 else if(['zip','sprite'].includes(extension)){spec=await importSprite(file);}
 else if(['webm','mp4'].includes(extension)){if(!session?.canConvert)throw new Error('動画の追加は公開サーバーのStudioで行ってください。');status('動画をSafari用に変換中…');const response=await fetch('/api/video?format='+extension,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-CSRF-Token':session.csrf||''},body:file});if(!response.ok)throw new Error((await response.json()).error||'動画変換に失敗');const result=await response.json();const name=crypto.randomUUID()+'.'+extension,fallback=crypto.randomUUID()+'.mp4';put(name,file);put(fallback,decodeBlob(result.content,'video/mp4'));spec=object('video',name,file.name,{fallback:{src:fallback,packedAlpha:result.packedAlpha},loop:true});}
 else throw new Error('GLB、WebM、MP4、Sprite ZIPに対応しています。');
 await addObject(spec);await saveDraft();media.play();status('作品を追加しました。XYZを編集するか、3D画面のハンドルをドラッグしてください。');});
function decodeBlob(content,type){const raw=atob(content);return new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type});}
async function encodeBlob(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});}
function selectedAssets(){return requiredAssets(project);}
async function snapshot(draft=false){project.id=$('scene-id').value;project.title=$('title').value;project.revision=crypto.randomUUID();validateScene(project,{draft});const files=[];for(const name of selectedAssets()){const blob=assets.get(name);if(!blob)throw new Error('素材が不足: '+name);files.push({name,content:await encodeBlob(blob)});}return validatePackage(structuredClone(project),files,{draft});}
async function loadData(data,draft=false){endPreview();audio.stopAll();audio.buffers.clear();validatePackage(data.scene,data.files,{draft});gizmo.detach();media.dispose();media.draco=new (await import('three/addons/loaders/DRACOLoader.js')).DRACOLoader();media.draco.setDecoderPath(new URL('./vendor/three/draco/',location.href).href);media.loader.setDRACOLoader(media.draco);for(const url of urls.values())URL.revokeObjectURL(url);assets.clear();urls.clear();for(const file of data.files)put(file.name,decodeBlob(file.content,''));project=toProject(data.scene,{draft});scene=project.scenes.find(s=>s.id===project.initialSceneId);markerId=project.markers[0]?.id||null;selected=null;$('scene-id').value=project.id;$('title').value=project.title;for(const s of project.scenes)for(const o of s.objects)await media.add(o);await refresh();media.time=0;await media.play();choose(null);}

async function loadPublished(id,base=new URL('./',location.href)){if(!sceneId(id))throw new Error('体験IDは半角小文字・数字・ハイフンで指定してください。');const dir=new URL('scenes/'+id+'/',base);const r=await fetch(new URL('scene.json',dir),{cache:'no-store'});if(!r.ok)throw new Error('シーンが見つかりません。');const s=validateScene(await r.json());const names=requiredAssets(s);const files=[];for(const name of names){const r=await fetch(new URL(name,dir));if(!r.ok)throw new Error('素材を取得できません: '+name);const blob=await r.blob();if(blob.size>MAX_ASSET_BYTES)throw new Error('素材サイズ超過');files.push({name,content:await encodeBlob(blob)});}await loadData({scene:s,files});await saveDraft();status('シーンを読み込みました。');}
$('sample').onclick=()=>task(()=>loadPublished('demo-interactive'));
$('scene-id').onchange=()=>{if(sceneId($('scene-id').value)){project.id=$('scene-id').value;saveDraft();}else status('体験IDは半角小文字・数字・ハイフンで指定してください。');};
$('title').onchange=()=>{project.title=$('title').value.slice(0,100);saveDraft();};
$('reload').onclick=()=>task(()=>loadPublished($('scene-id').value,new URL(session?.pagesURL||'./',location.href)));
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);}
$('save').onclick=()=>task(async()=>{const data=await snapshot(true);const zip=new JSZip();zip.file('scene.json',JSON.stringify(data.scene,null,2));for(const f of data.files)zip.file(f.name,f.content,{base64:true});download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),project.id+'-project.zip');await persistDraft();savedFingerprint=fingerprint();updateGuide();status('制作ZIPを保存しました。公開中の体験は更新していません。');});
$('restore').onchange=()=>task(async()=>{const file=$('restore').files[0];if(!file)return;if(file.size>MAX_TOTAL_BYTES)throw new Error('ZIPは48MB以内です。');const zip=await JSZip.loadAsync(file);if(!zip.file('scene.json'))throw new Error('制作ZIPではありません。');const text=await zip.file('scene.json').async('string');if(text.length>1000000)throw new Error('シーンデータが大きすぎます。');const s=validateScene(JSON.parse(text),{draft:true});const names=requiredAssets(s);const files=[];for(const name of names){const entry=zip.file(name);if(!entry)throw new Error('素材が不足: '+name);const content=await entry.async('base64');if(content.length>MAX_ASSET_BYTES*4/3)throw new Error('素材サイズ超過');files.push({name,content});}await loadData({scene:s,files},true);await saveDraft();status('制作データを復元しました。');});
async function task(fn){if(busy)return;busy=true;gizmo.enabled=false;const disabled=[...document.querySelectorAll('button,input,select')].map(e=>[e,e.disabled]);disabled.forEach(([e])=>e.disabled=true);try{await fn();}catch(e){status('処理を止めました: '+e.message);}finally{busy=false;gizmo.enabled=true;disabled.forEach(([e,was])=>e.disabled=was);syncFields();$('publish').disabled=!(session?.authenticated||session?.canLocalPublish);}}
$('logout').onclick=()=>task(async()=>{const r=await fetch('/api/logout',{method:'POST',headers:{'X-CSRF-Token':session.csrf}});if(!r.ok)throw new Error('接続終了に失敗しました。');location.reload();});
$('publish').onclick=()=>task(async()=>{
 if(!session?.authenticated&&!session?.canLocalPublish)throw new Error('公開サーバーでGitHubへ接続するか、localhostのStudioを開いてください。');
 for(const id of ['qr','public-link','copy','save-qr'])$(id).hidden=true;
 await persistDraft();savedFingerprint=fingerprint();const publicationFingerprint=fingerprint();
 const data=await snapshot();$('qr').hidden=true;$('public-link').hidden=true;$('copy').hidden=true;$('save-qr').hidden=true;status('GitHubへ送信しています…');
 const r=await fetch(session?.canLocalPublish&&!session?.authenticated?'/api/local-publish':'/api/publish',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:JSON.stringify({scene:data.scene,files:data.files})});const job=await r.json();if(!r.ok)throw new Error(job.error||'送信に失敗');
 sessionStorage.setItem('webar-publish-job',job.id);await watch(job.id);publishedFingerprint=publicationFingerprint;updateGuide();goStep(2);
});
async function watch(id){for(let i=0;i<120;i++){const r=await fetch('/api/jobs/'+encodeURIComponent(id));const job=await r.json();if(!r.ok)throw new Error(job.error||'公開状態を取得できません');status(job.message);if(job.state==='failed'){sessionStorage.removeItem('webar-publish-job');throw new Error(job.message);}if(job.state==='ready'){publishedURL=job.url;await QRCode.toCanvas($('qr'),job.url,{width:240,margin:2,errorCorrectionLevel:'M'});$('qr').hidden=false;$('public-link').href=job.url;$('public-link').textContent=job.url;$('public-link').hidden=false;$('copy').hidden=false;$('save-qr').hidden=false;sessionStorage.removeItem('webar-publish-job');return;}await new Promise(r=>setTimeout(r,5000));}throw new Error('公開確認が継続中です。画面を再読込すると確認を再開します。');}
$('copy').onclick=()=>navigator.clipboard.writeText(publishedURL).then(()=>status('URLをコピーしました。')).catch(()=>status('表示されたURLをコピーしてください。'));
$('save-qr').onclick=()=>$('qr').toBlob(blob=>download(blob,project.id+'-qr.png'));
function options(el,values,value){el.replaceChildren();for(const [id,label] of values){const o=document.createElement('option');o.value=id;o.textContent=label;el.append(o);}el.value=value||'';}
async function refresh(){updateShadow();const selectedId=selected?.id;choose(null);options($('marker-select'),project.markers.map(m=>[m.id,m.name]),markerId);options($('scene-select'),project.scenes.map(s=>[s.id,s.name]),scene.id);$('marker-summary').textContent='登録 '+project.markers.length+'枚 / 同時追跡 '+project.maxTrack+'枚 / このシーンの配置：'+project.markers.map(m=>m.name+' '+scene.objects.filter(o=>o.markerId===m.id).length+'作品').join('、');$('scene-name').value=scene.name;$('lost').value=scene.markerLost;$('auto-next').value=scene.autoNextSeconds;options($('scene-next'),[['','切替なし'],...project.scenes.map(s=>[s.id,s.name])],scene.nextSceneId);for(const s of project.scenes)for(const o of s.objects){const i=media.items.get(o.id);if(i){i.group.visible=s===scene&&o.markerId===markerId;media.setGate(o.id,i.group.visible);}}await showMarker();if(selectedId&&scene.objects.some(o=>o.id===selectedId&&o.markerId===markerId))choose(selectedId);else{syncFields();list();}}
function syncInteraction(){const o=selected;for(const id of ['autoplay','tap-action','clip','tap-loop','effect','effect-duration','sound-select','volume','tap-next','tap-delay','object-marker','test-tap'])$(id).disabled=!o;
 $('autoplay').checked=o?.autoplay??true;$('tap-action').value=o?.interaction.action||'none';const clips=media.items.get(o?.id)?.clips||[];options($('clip'),[['all','全アニメーション'],...clips.map(c=>[c.name,c.name])],o?.interaction.clip||'all');$('tap-loop').checked=o?.interaction.loop??false;$('effect').value=o?.interaction.effect||'none';$('effect-duration').value=o?.interaction.duration||1;options($('sound-select'),[['','音なし'],...project.sounds.map(s=>[s.id,s.name])],o?.interaction.soundId);$('volume').value=o?.interaction.volume??1;options($('tap-next'),[['','切替なし'],...project.scenes.map(s=>[s.id,s.name])],o?.interaction.nextSceneId);$('tap-delay').value=o?.interaction.delay??1;options($('object-marker'),project.markers.map(m=>[m.id,m.name]),o?.markerId);}
for(const id of ['autoplay','tap-action','clip','tap-loop','effect','effect-duration','sound-select','volume','tap-next','tap-delay','object-marker'])$(id).onchange=()=>{if(!selected)return;const i=selected.interaction;selected.autoplay=$('autoplay').checked;i.action=$('tap-action').value;i.clip=$('clip').value;i.loop=$('tap-loop').checked;i.effect=$('effect').value;i.duration=Math.min(60,Math.max(.1,Number($('effect-duration').value)||1));i.soundId=$('sound-select').value||null;i.volume=Math.min(1,Math.max(0,Number($('volume').value)||0));i.nextSceneId=$('tap-next').value||null;i.delay=Math.min(60,Math.max(0,Number($('tap-delay').value)||0));selected.markerId=$('object-marker').value;media.reset(selected.id);saveDraft();refresh();};
$('test-tap').onclick=()=>task(async()=>{if(!selected)return;if(!tapEnabled(selected))throw new Error('この作品のタップはOFFです。左の一覧でONにしてください。');const o=selected;await audio.load(project.sounds);await audio.unlock();media.playing=true;if(o.interaction.action==='restart')await media.restart(o.id);else if(o.interaction.action==='toggle')await media.setPlaying(o.id,!media.items.get(o.id).playing);media.effect(o.id);if(o.interaction.action!=='toggle'||media.items.get(o.id).playing)await audio.play(o);else audio.stop(o.id);status('動きと音を確認しました。シーン切替は「再生 / 停止」のプレビューで確認してください。');});
$('marker-select').onchange=()=>{markerId=$('marker-select').value;refresh();};
$('scene-select').onchange=()=>{const id=$('scene-select').value;endPreview();scene=project.scenes.find(s=>s.id===id);refresh();saveDraft();};
$('add-scene').onclick=()=>task(async()=>{endPreview();if(project.scenes.length>=12)throw new Error('シーンは12個までです。');scene={id:crypto.randomUUID(),name:'シーン'+(project.scenes.length+1),autoNextSeconds:0,nextSceneId:null,markerLost:'continue',objects:[]};project.scenes.push(scene);await refresh();saveDraft();});
$('delete-scene').onclick=()=>{endPreview();if(project.scenes.length===1)return status('最後のシーンは削除できません。');const id=scene.id;for(const o of scene.objects)media.remove(o.id);project.scenes=project.scenes.filter(s=>s.id!==id);for(const s of project.scenes){if(s.nextSceneId===id){s.nextSceneId=null;s.autoNextSeconds=0;}for(const o of s.objects)if(o.interaction.nextSceneId===id)o.interaction.nextSceneId=null;}if(project.initialSceneId===id)project.initialSceneId=project.scenes[0].id;scene=project.scenes[0];refresh();saveDraft();};
$('initial-scene').onclick=()=>{project.initialSceneId=scene.id;saveDraft();status(scene.name+'を開始シーンに設定しました。');};
for(const id of ['scene-name','lost','auto-next','scene-next'])$(id).onchange=()=>{scene.name=$('scene-name').value.slice(0,100)||'シーン';scene.markerLost=$('lost').value;scene.autoNextSeconds=Math.min(3600,Math.max(0,Number($('auto-next').value)||0));scene.nextSceneId=$('scene-next').value||null;saveDraft();refresh();};
$('sound-file').onchange=()=>task(async()=>{const file=$('sound-file').files[0];if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!['mp3','wav','m4a','aac'].includes(ext))throw new Error('MP3/WAV/M4A/AACを使用してください。');if(project.sounds.length>=24)throw new Error('音は24個までです。');const id=crypto.randomUUID(),name=id+'.'+ext;put(name,file);const sound={id,name:file.name.slice(0,100),src:name};await audio.load([sound]);project.sounds.push(sound);syncInteraction();saveDraft();status('音を登録しました。作品の「タップ時の音」で選択してください。');});
const dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('webar-art-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('draft');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
let saveTimer,draftSequence=0;
function fingerprint(){const p=structuredClone(project);delete p.revision;return JSON.stringify(p);}
function localDraft(){return {scene:structuredClone(project),files:selectedAssets().filter(name=>assets.has(name)).map(name=>({name,blob:assets.get(name)}))};}
async function persistDraft(){clearTimeout(saveTimer);const seq=++draftSequence,db=await dbPromise;const data=localDraft();await new Promise((resolve,reject)=>{const tx=db.transaction('draft','readwrite');tx.objectStore('draft').put(data,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('保存が中断されました'));});if(seq===draftSequence)$('save-state').textContent='ブラウザー保存済み '+new Date().toLocaleTimeString();}
function saveDraft(){clearTimeout(saveTimer);if($('save-state'))$('save-state').textContent='変更を保存中…';updateGuide();saveTimer=setTimeout(()=>persistDraft().catch(e=>{status('自動保存できません。制作ZIPを保存してください：'+e.message);$('save-state').textContent='保存に失敗しました';}),400);}
setupGuide();
async function init(){try{const r=await fetch('/api/session');if(r.ok)session=await r.json();}catch{}
 $('publish').disabled=!(session?.authenticated||session?.canLocalPublish);$('login').hidden=!session?.oauthAvailable||session?.authenticated;$('logout').hidden=!session?.authenticated;$('connection').textContent=session?.authenticated?'GitHub接続済み: '+session.login+' → '+session.repository:session?.canConvert?'ローカル編集。直接公開にはGitHub接続が必要です。':'GitHub Pages上の編集。直接公開は公開サーバーで行ってください。';
 try{const db=await dbPromise;const data=await new Promise((resolve,reject)=>{const req=db.transaction('draft').objectStore('draft').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(data?.scene&&(data.scene.version===2||data.scene?.marker&&data.scene.objects.length)){const files=[];for(const f of data.files)files.push({name:f.name,content:await encodeBlob(f.blob)});await loadData({scene:data.scene,files},true);status('前回のブラウザー保存を復元しました。公開中の体験とは別の編集データです。');}else await loadPublished('demo-interactive');}catch(e){status('マーカー画像と作品を登録してください。'+e.message);}
 await refresh();updateGuide();
 const job=sessionStorage.getItem('webar-publish-job');if(job&&(session?.authenticated||session?.canLocalPublish))task(()=>watch(job));
}
init();

function element(tag,attrs={},text=''){const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);e.textContent=text;return e;}
function setupGuide(){
 const header=document.querySelector('header');const top=element('div',{class:'project-actions'});top.innerHTML='<span id="save-state" role="status">ブラウザー自動保存</span><button id="guided-save">保存</button><button id="guided-publish">公開へ</button>';header.append(top);
 const nav=element('nav',{'aria-label':'制作の手順',class:'workflow-nav'});WORKSPACES.forEach((name,i)=>{const b=element('button',{'data-step':i},(i+1)+'. '+name);b.onclick=()=>goStep(i);nav.append(b);});header.after(nav);
 const banner=element('section',{class:'guide-banner','aria-live':'polite'});banner.innerHTML='<strong id="guide-title"></strong><p id="guide-text"></p><div id="breadcrumb"></div>';nav.after(banner);
 const left=document.querySelector('main>aside'),right=document.querySelector('aside.right');const leftNodes=[...left.childNodes],rightNodes=[...right.childNodes];left.replaceChildren();right.replaceChildren();
 const panels=[];for(let i=0;i<6;i++){const e=element('section',{'data-panel':i});panels.push(e);left.append(e);}
 let stage=0;for(const node of leftNodes){if(node.nodeType===1&&node.tagName==='H2')stage=node.textContent.startsWith('1.')?0:node.textContent.startsWith('2.')?0:1;if(node.nodeType===1&&(node.id==='save'||node.contains?.($('restore'))))stage=3;panels[stage].append(node);}
 // Scene management remains visible within placement, separated from object controls.
 const config=element('div',{id:'object-config'}),reaction=element('div',{id:'reaction-config'}),publication=element('div',{id:'publish-config'});right.append(config,reaction,publication);let area=config;
 for(const node of rightNodes){if(node.nodeType===1&&node.tagName==='H2'){if(node.textContent==='タップ反応')area=reaction;if(node.textContent==='4. 公開')area=publication;}area.append(node);}
 publication.querySelector('h2').textContent='保存・公開';banner.append($('status'));
 const selectedLabel=element('p',{id:'selected-label',class:'selection-title'},'作品を選択してください');right.prepend(selectedLabel);
 const tools=element('div',{class:'inspector-tools'});tools.append($('move'),$('rotate'),$('scale'));config.prepend(tools);const previewTools=element('div',{class:'preview-tools'});previewTools.append(element('p',{},'シーンのプレビュー'),$('preview'));right.append(previewTools);
 const chain=element('button',{id:'scale-chain',type:'button','aria-pressed':'true'},'🔗 連動 ON');$('transform').append(chain);chain.onclick=()=>{if(!selected)return;selected.scaleLinked=selected.scaleLinked===false;saveDraft();syncFields();};
 const shadow=element('label');shadow.innerHTML='<input id="shadow-on" type="checkbox">作品の影を表示';config.append(shadow);const strength=element('label',{},'影の濃さ（全作品）');strength.innerHTML+='<input id="shadow-opacity" type="range" min="0" max="100" value="30">';config.append(strength);const direction=element('label',{},'影の方向（全作品）');direction.innerHTML+='<select id="shadow-direction"><option value="back">奥（マーカー上側）</option><option value="front">手前（マーカー下側）</option><option value="left">左</option><option value="right">右</option></select>';config.append(direction);const extent=element('label',{},'影を受ける範囲（マーカーの倍率）');extent.innerHTML+='<input id="shadow-extent" type="number" min="1" max="8" step="0.5" value="4">';config.append(extent);$('shadow-direction').onchange=()=>{project.shadowDirection=$('shadow-direction').value;updateShadow();saveDraft();};$('shadow-extent').onchange=()=>{const n=Number($('shadow-extent').value);project.shadowExtent=Number.isFinite(n)?Math.max(1,Math.min(8,n)):4;$('shadow-extent').value=project.shadowExtent;updateShadow();saveDraft();};$('shadow-on').onchange=()=>{if(!selected)return;selected.shadow=$('shadow-on').checked;media.apply(selected);updateShadow();saveDraft();};$('shadow-opacity').oninput=()=>{project.shadowOpacity=Number($('shadow-opacity').value)/100;updateShadow();saveDraft();};
 const switching=element('fieldset',{class:'scene-switch-card'});const legend=element('legend',{},'タップでシーンを切り替える');const enabled=element('label');enabled.innerHTML='<input id="scene-switch-on" type="checkbox">シーン切替 ON';switching.append(legend,enabled,$('tap-next').closest('label'),$('tap-delay').closest('label'));reaction.append(switching);$('scene-switch-on').onchange=()=>{if(!selected)return;const next=project.scenes.find(s=>s.id!==scene.id);if($('scene-switch-on').checked&&!next){$('scene-switch-on').checked=false;return status('マーカー・シーンで切替先を追加し、配置・反応で作品を配置してください。');}selected.interaction.nextSceneId=$('scene-switch-on').checked?(selected.interaction.nextSceneId||next.id):null;saveDraft();syncFields();};
 const opacity=element('label',{},'不透明度（作品全体）');opacity.innerHTML+=' <output id="opacity-value">100%</output><input id="opacity" type="range" min="0" max="100" value="100">';config.append(opacity);$('opacity').oninput=()=>{if(!selected)return;selected.opacity=Number($('opacity').value)/100;$('opacity-value').textContent=$('opacity').value+'%';media.apply(selected);saveDraft();};
 const only=element('button',{id:'exclusive-tap'},'この作品だけにタップ反応を限定');only.onclick=()=>{if(!selected)return status('中央または作品一覧で宝石を選択してください。');exclusiveReaction(scene,selected.id);syncInteraction();saveDraft();status('このシーンの「'+selected.name+'」以外のタップ反応を解除しました。自動再生は維持します。');};only.hidden=true;reaction.append(only);config.append($('duplicate'),$('delete'));
 const advanced=$('pair-marker').closest('details');advanced.open=false;advanced.querySelector('summary').textContent='詳細：2マーカー同時表示';
 reaction.prepend(element('p',{id:'reaction-summary',class:'hint'}));
 const reactionHint=element('p',{class:'hint'},'きっかけ：選択作品のタップ。以下で動作・音・切替を設定します。音声入力はこの版の対象外です。');reaction.prepend(reactionHint);
 panels[2].append(element('h2',{},'タップ反応'),element('p',{class:'hint'},'作品一覧で宝石を選択 → 右側で動きと音を指定 → 左の一覧で宝石をタップON、他作品をOFF → 反応をテスト。'));const objectHost=element('div',{id:'object-list-host'});left.append(objectHost);objectHost.append($('objects'));
 const fresh=element('button',{id:'new-project'},'空のプロジェクトを作成');fresh.onclick=()=>task(async()=>{if(!confirm('現在の編集を空のプロジェクトへ切り替えます。必要な制作ZIPは保存しましたか？'))return;endPreview();media.dispose();media.draco=new(await import('three/addons/loaders/DRACOLoader.js')).DRACOLoader();media.draco.setDecoderPath(new URL('./vendor/three/draco/',location.href).href);media.loader.setDRACOLoader(media.draco);for(const u of urls.values())URL.revokeObjectURL(u);urls.clear();assets.clear();project={version:2,id:'art-003',title:'新しいWebAR Art',revision:'draft',trackingTarget:'pending.mind',maxTrack:1,markers:[],sounds:[],initialSceneId:'scene-1',scenes:[{id:'scene-1',name:'シーン1',autoNextSeconds:0,nextSceneId:null,markerLost:'continue',objects:[]}]};scene=project.scenes[0];markerId=null;selected=null;publishedURL='';publishedFingerprint='';savedFingerprint='';for(const id of ['qr','public-link','copy','save-qr'])$(id).hidden=true;$('scene-id').value=project.id;$('title').value=project.title;await refresh();await persistDraft();goStep(0);status('空のプロジェクトを作成しました。マーカー画像を登録してください。');});panels[0].prepend(fresh);
 panels[3].prepend(element('h2',{},'編集内容を保存'),element('p',{class:'hint'},'ブラウザー自動保存・制作ZIP・サーバー保存を区別します。保存では公開版は更新しません。'));
 const disk=element('button',{id:'disk-save'},'サーバーに保存');const open=element('button',{id:'disk-open'},'サーバーの保存を開く');panels[3].append(disk,open);disk.onclick=()=>task(async()=>{if(!session?.canSaveDraft)throw new Error('localhostまたはGitHub接続済みの公開サーバーで保存してください。');const data=await snapshot(true);const r=await fetch('/api/drafts/'+encodeURIComponent(project.id),{method:'PUT',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf||''},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error);await persistDraft();savedFingerprint=fingerprint();$('save-state').textContent='サーバー保存済み '+new Date(result.savedAt).toLocaleTimeString();updateGuide();status('サーバーへ保存しました。公開版は変更していません。');});open.onclick=()=>task(async()=>{const r=await fetch('/api/drafts/'+encodeURIComponent($('scene-id').value));const data=await r.json();if(!r.ok)throw new Error(data.error||'サーバー保存が見つかりません');await loadData(data,true);await persistDraft();savedFingerprint=fingerprint();updateGuide();status('サーバーの保存を開きました。');});
 panels[4].append(element('h2',{},'公開版を更新'),element('p',{class:'hint'},'右側で体験IDとタイトルを設定します。localhostではMacのGit認証を使い、公開サーバーではGitHub接続を使います。公開完了後、QRが表示されます。'));
 const setup=element('details');setup.innerHTML='<summary>接続・公開の初回設定</summary><p class="hint">Mac：APPLY.shで適用した後、このlocalhost Studioを使うと既存のGit認証で公開できます。GitHub Pages上のStudioでは直接公開できません。Renderを使う場合：README_SETUP_JA.mdの「GitHub直接公開」を設定し、GitHubへ接続します。</p><p class="hint">Renderで制作途中の保存を永続化するにはPersistent Diskを /var/data に接続し、DRAFT_DIR=/var/data/webar-drafts を指定します。未設定のディスク保存は再デプロイで消える場合があります。</p>';panels[4].append(setup);
 panels[5].innerHTML='<h2>公開後：iPhoneで体験</h2><ol><li>公開完了後、右のQRをiPhoneのカメラで読み取る。</li><li>Safariで「ARを開始」を押し、カメラを許可。</li><li>PCで「マーカーを表示・印刷」を押し、表示画像または紙へカメラを向ける。</li><li>宝石をタップして動きと音を確認。ほかの作品をタップしても反応しないことを確認。</li></ol><p class="hint">QRの表示は配信確認の完了を意味します。実際の追跡・音はiPhoneで確認してください。</p>';
 const print=element('button',{},'マーカーを表示・印刷');print.onclick=()=>$('print').click();panels[5].append(print);
 const bottom=element('div',{class:'step-controls'});const back=element('button',{},'前へ'),next=element('button',{},'次へ');back.onclick=()=>goStep(Math.max(0,activeStep-1));next.onclick=()=>{if(activeStep===0&&!project.markers.length)return status('先にマーカー画像を登録してください。');if(activeStep===1&&!scene.objects.length)return status('先に作品を追加してください。');goStep(Math.min(2,activeStep+1));};bottom.append(back,next);left.append(bottom);
 $('guided-save').onclick=()=>goStep(2);$('guided-publish').onclick=()=>goStep(2);goStep(0);
}
function goStep(i){activeStep=i;document.querySelectorAll('[data-panel]').forEach(e=>{const n=Number(e.dataset.panel);e.hidden=!(i===0?n===0:i===1?n===1||n===2:n>=3);});document.querySelectorAll('[data-step]').forEach(e=>{e.classList.toggle('selected',Number(e.dataset.step)===i);e.setAttribute('aria-current',Number(e.dataset.step)===i?'step':'false');});$('object-config').hidden=i!==1;$('reaction-config').hidden=i!==1;$('publish-config').hidden=i!==2;$('object-list-host').hidden=i!==1;updateGuide();}
function updateGuide(){if(!$('guide-title'))return;$('guide-title').textContent=(activeStep+1)+'. '+WORKSPACES[activeStep];$('guide-text').textContent=['マーカーを登録し、同じ画面でシーンを作成・選択します。作品は次の画面で配置します。','作品を選択し、配置とタップ反応を同じ右パネルで編集します。動画・Spriteも透過の輪郭に沿った影を設定できます。','編集データの保存と、公開版の更新を同じ画面で行います。公開完了後のQRでiPhoneを開いてください。'][activeStep];$('breadcrumb').textContent=project.title+' ＞ '+(marker()?.name||'マーカー未登録')+' ＞ '+scene.name+' ＞ '+(selected?.name||'作品未選択');$('selected-label').textContent=selected?'選択作品：'+selected.name:'作品を選択してください';$('reaction-summary').textContent=reactionText(selected,project);$('exclusive-tap').disabled=!selected;$('connection').textContent=session?.authenticated?'GitHub接続済み：'+session.repository:session?.canLocalPublish?'MacのGit認証で直接公開できます。':'直接公開にはlocalhostまたはGitHub接続済みサーバーが必要です。';if(publishedURL)$('guide-text').textContent+=' '+(publishedFingerprint&&publishedFingerprint!==fingerprint()?'未公開の変更があります。':'公開URL：'+publishedURL);}

function updateShadow(){const enabled=scene.objects.some(o=>o.shadow);renderer.shadowMap.enabled=enabled;renderer.shadowMap.type=THREE.PCFShadowMap;const settings=shadowSettings(project);light.position.set(...shadowLightPosition(settings.direction));configureShadowLight(light,shadowBounds(marker()?.aspect??1,settings.extent));light.castShadow=enabled;if(shadowPlane){shadowPlane.scale.set(settings.extent,settings.extent,1);shadowPlane.visible=enabled;shadowPlane.material.opacity=project.shadowOpacity??.3;}}
