export function shadowSettings(project={}){return{direction:project.shadowDirection??'back',extent:project.shadowExtent??4};}
export function shadowLightPosition(direction='back'){return({back:[0,-2,3],front:[0,2,3],left:[2,0,3],right:[-2,0,3]})[direction]??[0,-2,3];}
export function shadowBounds(aspect=1,extent=4){return Math.max(4,extent*Math.max(1,aspect)/2+1);}
// Light and target use marker-local coordinates so AR camera distance cannot move the marker out of the shadow camera.
export function configureShadowLight(light,bound=4){light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{near:.01,far:bound*4,left:-bound,right:bound,top:bound,bottom:-bound});light.shadow.bias=-.0002;light.shadow.normalBias=.002;light.shadow.camera.updateProjectionMatrix();}
export function createMarkerShadowRig(THREE,group,aspect,opacity=.3,options={}){const settings=shadowSettings(options);const bound=shadowBounds(aspect,settings.extent);const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(...shadowLightPosition(settings.direction));const target=new THREE.Object3D();group.add(light,target);light.target=target;configureShadowLight(light,bound);const receiver=new THREE.Mesh(new THREE.PlaneGeometry(settings.extent,aspect*settings.extent),new THREE.ShadowMaterial({opacity,depthWrite:false,side:THREE.DoubleSide}));receiver.position.z=.002;receiver.receiveShadow=true;receiver.raycast=()=>{};group.add(receiver);return{light,receiver,target,group,bound};}
export function patchPackedAlphaDepth(shader){if(!shader.fragmentShader.includes('#include <map_fragment>'))throw new Error('Packed-alpha shadow shader incompatible');shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',`#ifdef USE_MAP
 diffuseColor.a *= texture2D(map,vec2(0.5+vMapUv.x*0.5,vMapUv.y)).r;
 #endif`);}

export function fitMarkerShadowRig(rig,THREE){rig.group.updateMatrixWorld(true);const scale=rig.group.getWorldScale(new THREE.Vector3());const unit=Math.max(Math.abs(scale.x),Math.abs(scale.y),Math.abs(scale.z));if(!Number.isFinite(unit)||unit<=0)return;const bound=rig.bound??4;const camera=rig.light.shadow.camera;Object.assign(camera,{near:.01*unit,far:bound*4*unit,left:-bound*unit,right:bound*unit,top:bound*unit,bottom:-bound*unit});rig.light.shadow.normalBias=.002*unit;camera.updateProjectionMatrix();}
