import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {validatePackage} from '../studio/schema.js';
const exec=promisify(execFile);
export class LocalPublisher {
 constructor({root,owner,repo,pagesURL}){Object.assign(this,{root,owner,repo,pagesURL});}
 async git(...args){return (await exec('git',args,{cwd:this.root,timeout:60000,maxBuffer:1024*1024})).stdout.trim();}
 async publish(data){validatePackage(data.scene,data.files);const remote=await this.git('remote','get-url','origin');if(![ `https://github.com/${this.owner}/${this.repo}`,`https://github.com/${this.owner}/${this.repo}.git`,`git@github.com:${this.owner}/${this.repo}.git`].includes(remote))throw new Error('Git originが設定された公開先と一致しません。');const branch=await this.git('branch','--show-current');if(branch!==(process.env.GITHUB_BRANCH||'main'))throw new Error('公開ブランチmainでStudioを起動してください。');const path='public/scenes/'+data.scene.id;await mkdir(join(this.root,path),{recursive:true});for(const f of data.files)await writeFile(join(this.root,path,f.name),Buffer.from(f.content,'base64'));await writeFile(join(this.root,path,'scene.json'),JSON.stringify(data.scene,null,2));await this.git('add','--',path);await this.git('commit','--only','-m','Publish WebAR Art '+data.scene.id,'--',path);await this.git('push','origin',branch);const url=new URL('ar.html',this.pagesURL);url.searchParams.set('scene',data.scene.id);return{mode:'local',sceneId:data.scene.id,revision:data.scene.revision,files:data.files.map(f=>({name:f.name,size:Buffer.from(f.content,'base64').length})),url:url.href};}
 async status(job){try{const base=new URL('scenes/'+job.sceneId+'/',this.pagesURL);const manifest=await fetch(new URL('scene.json?verify='+Date.now(),base),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!manifest.ok||(await manifest.json()).revision!==job.revision)return{state:'waiting',message:'GitHub Pagesの更新を待っています…'};for(const f of job.files){const r=await fetch(new URL(f.name+'?verify='+Date.now(),base),{method:'HEAD',cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok||Number(r.headers.get('content-length'))!==f.size)return{state:'waiting',message:'作品素材の配信を確認中…'};}const page=await fetch(job.url,{signal:AbortSignal.timeout(15000)});if(!page.ok)return{state:'waiting',message:'ARページの配信を確認中…'};return{state:'ready',message:'公開完了。QRをiPhoneで読み取ってください。',url:job.url};}catch{return{state:'waiting',message:'配信確認を再試行しています…'};}}
}
