import {createServer} from 'node:http';
import {randomBytes} from 'node:crypto';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {GitHubPublisher} from './github.mjs';
import {convertVideo} from './video.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const port=Number(process.env.PORT||8080),host=process.env.HOST||(process.env.RENDER?'0.0.0.0':'127.0.0.1');
const origin=(process.env.APP_ORIGIN||'http://localhost:'+port).replace(/\/$/,'');
const local=new URL(origin).hostname==='localhost'||new URL(origin).hostname==='127.0.0.1';
const owner=process.env.GITHUB_OWNER||'correctree',repo=process.env.GITHUB_REPO||'webar-art',branch=process.env.GITHUB_BRANCH||'main';
const clientId=process.env.GITHUB_CLIENT_ID,clientSecret=process.env.GITHUB_CLIENT_SECRET;
const allowed=(process.env.GITHUB_ALLOWED_LOGINS||'correctree').split(',').map(s=>s.trim().toLowerCase());
const publisher=new GitHubPublisher({owner,repo,branch});const sessions=new Map(),states=new Map(),jobs=new Map();let publishing=false,converting=false;
const cookie=(name,value,age=7200)=>name+'='+value+'; HttpOnly; SameSite=Lax; Path=/; Max-Age='+age+(local?'':'; Secure');
function send(res,code,data){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function redirect(res,url,headers={}){res.writeHead(302,{Location:url,...headers});res.end();}
function getCookie(req,name){return req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1);}
function getSession(req){const s=sessions.get(getCookie(req,'webar_session'));return s&&s.expires>Date.now()?s:null;}
function protect(req,session,{convert=false}={}){if(req.headers.origin!==origin)throw Object.assign(new Error('送信元を確認できません。APP_ORIGINを確認してください。'),{status:403});if(!session){if(convert&&local)return;throw Object.assign(new Error('GitHub接続が必要です。'),{status:401});}if(req.headers['x-csrf-token']!==session.csrf)throw Object.assign(new Error('画面を再読み込みしてください。'),{status:403});}
async function body(req,max){let size=0;const parts=[];for await(const part of req){size+=part.length;if(size>max)throw Object.assign(new Error('送信データが大きすぎます。'),{status:413});parts.push(part);}return Buffer.concat(parts);}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.glb':'model/gltf-binary','.mp4':'video/mp4','.webm':'video/webm','.wasm':'application/wasm','.mind':'application/octet-stream','.txt':'text/plain'};
export const server=createServer(async(req,res)=>{try{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');const url=new URL(req.url,origin),session=getSession(req);
 if(url.pathname==='/health'){return send(res,200,{ok:true});}
 if(url.pathname==='/api/session'&&req.method==='GET'){return send(res,200,{authenticated:!!session,login:session?.login,csrf:session?.csrf,repository:owner+'/'+repo,oauthAvailable:!!(clientId&&clientSecret),canConvert:!!session||local,pagesURL:'https://'+owner.toLowerCase()+'.github.io/'+(repo.toLowerCase()===owner.toLowerCase()+'.github.io'?'':repo+'/')});}
 if(url.pathname==='/auth/login'&&req.method==='GET'){if(!clientId||!clientSecret)throw new Error('GitHub Appの初回設定が必要です。README_SETUP_JA.mdを確認してください。');const state=randomBytes(32).toString('hex');states.set(state,Date.now()+600000);const auth=new URL('https://github.com/login/oauth/authorize');auth.searchParams.set('client_id',clientId);auth.searchParams.set('redirect_uri',origin+'/auth/callback');auth.searchParams.set('state',state);return redirect(res,auth.href,{'Set-Cookie':cookie('webar_oauth',state,600)});}
 if(url.pathname==='/auth/callback'&&req.method==='GET'){const state=url.searchParams.get('state');if(!state||state!==getCookie(req,'webar_oauth')||(states.get(state)||0)<Date.now())throw new Error('認証確認が期限切れです。再接続してください。');states.delete(state);const code=url.searchParams.get('code');if(!code)throw new Error('GitHub認証が完了しませんでした。');const response=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:clientId,client_secret:clientSecret,code,redirect_uri:origin+'/auth/callback'}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok||!result.access_token)throw new Error('GitHub認証に失敗しました。');const user=await publisher.request(result.access_token,'/user');if(!allowed.includes(user.login.toLowerCase()))throw new Error('このアカウントは公開者として登録されていません。');const id=randomBytes(32).toString('hex');sessions.set(id,{token:result.access_token,login:user.login,csrf:randomBytes(32).toString('hex'),expires:Date.now()+7200000});return redirect(res,'/studio.html',{'Set-Cookie':[cookie('webar_session',id),cookie('webar_oauth','',0)]});}
 if(url.pathname==='/api/logout'&&req.method==='POST'){protect(req,session);sessions.delete(getCookie(req,'webar_session'));res.setHeader('Set-Cookie',cookie('webar_session','',0));return send(res,200,{ok:true});}
 if(url.pathname==='/api/video'&&req.method==='POST'){protect(req,session,{convert:true});if(converting)throw new Error('別の動画を変換中です。少し待ってください。');converting=true;try{const bytes=await body(req,24*1024*1024);return send(res,200,await convertVideo(bytes,url.searchParams.get('format')));}finally{converting=false;}}
 if(url.pathname==='/api/publish'&&req.method==='POST'){protect(req,session);if(publishing)throw new Error('別の公開処理が進行中です。');publishing=true;try{const data=JSON.parse((await body(req,70*1024*1024)).toString());const result=await publisher.publish(session.token,data);const id=randomBytes(16).toString('hex');jobs.set(id,{...result,id,login:session.login,created:Date.now(),state:'waiting'});return send(res,202,{id,sha:result.sha});}finally{publishing=false;}}
 if(url.pathname.startsWith('/api/jobs/')&&req.method==='GET'){if(!session)throw Object.assign(new Error('GitHubへ再接続してください。'),{status:401});const job=jobs.get(url.pathname.slice('/api/jobs/'.length));if(!job||job.login!==session.login)throw Object.assign(new Error('公開確認情報がありません。サーバー再起動後は公開版を確認してください。'),{status:404});if(job.state==='ready'||job.state==='failed')return send(res,200,job);const result=await publisher.status(session.token,job);Object.assign(job,result);return send(res,200,job);}
 if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/auth/'))return send(res,404,{error:'APIがありません。'});
 if(!['GET','HEAD'].includes(req.method))return send(res,405,{error:'許可されていない操作です。'});
 const relative=decodeURIComponent(url.pathname==='/'?'/studio.html':url.pathname);const base=resolve(root,'dist'),file=resolve(base,'.'+relative);
 if(!file.startsWith(base+sep)||relative.split('/').some(part=>part.startsWith('.')))return send(res,403,{error:'アクセスできません。'});
 const info=await stat(file);if(!info.isFile())return send(res,404,{error:'ファイルがありません。'});res.setHeader('Content-Type',mime[extname(file)]||'application/octet-stream');res.setHeader('Accept-Ranges','bytes');
 let start=0,end=info.size-1,code=200;const range=req.headers.range;if(range){const match=/^bytes=(\d+)-(\d*)$/.exec(range);if(!match)return send(res,416,{error:'Range不正'});start=Number(match[1]);end=match[2]?Math.min(Number(match[2]),end):end;if(start>end||start>=info.size)return send(res,416,{error:'Range不正'});code=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${info.size}`);}res.setHeader('Content-Length',end-start+1);res.writeHead(code);if(req.method==='HEAD')return res.end();const {createReadStream}=await import('node:fs');createReadStream(file,{start,end}).on('error',()=>res.destroy()).pipe(res);
 }catch(error){if(!res.headersSent)send(res,error.status||400,{error:error.code==='ENOENT'?'ファイルがありません。':error.message});else res.destroy();}});
setInterval(()=>{const now=Date.now();for(const[id,s]of sessions)if(s.expires<now)sessions.delete(id);for(const[id,t]of states)if(t<now)states.delete(id);for(const[id,j]of jobs)if(now-j.created>86400000)jobs.delete(id);},60000).unref();
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))server.listen(port,host,()=>console.log('WebAR Art Studio: '+origin+'/studio.html'));
